import type { Metadata } from "next";

/**
 * Canonical origin of this site, used for `metadataBase`, the sitemap and
 * robots.txt. The root domain is not bought yet, so production falls back to
 * the Vercel URL; set NEXT_PUBLIC_SITE_URL once the real domain is live.
 */
const PROD = process.env.NODE_ENV === "production";
const FALLBACK = PROD ? "https://drinks-on-chain-landing.vercel.app" : "http://localhost:3001";

export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || FALLBACK).replace(/\/$/, "");

export const SITE_NAME = "Drinks on Chain";
export const SITE_TAGLINE = "Cada botella, con su lugar y su historia.";

/** Absolute URL of a path on this site. */
export const siteUrl = (path = "/") => `${SITE_URL}${path === "/" ? "" : path}`;

/** Default share image generated by `app/opengraph-image.tsx`. */
const OG_IMAGE = { url: "/opengraph-image", type: "image/png", width: 1200, height: 630, alt: `${SITE_NAME} · ${SITE_TAGLINE}` };

/**
 * Full metadata for a public page. Nested fields such as `openGraph` are
 * replaced (not merged) by child segments, so each page restates them,
 * including the image: the root `opengraph-image` file only reaches pages
 * that do not declare their own `openGraph`.
 */
export function pageMetadata({ path, title, description }: { path: string; title?: string; description: string }): Metadata {
  const fullTitle = title ? `${title} · ${SITE_NAME}` : `${SITE_NAME} · ${SITE_TAGLINE}`;
  return {
    title: title ?? { absolute: fullTitle },
    description,
    alternates: { canonical: path },
    openGraph: {
      title: fullTitle,
      description,
      url: path,
      siteName: SITE_NAME,
      type: "website",
      locale: "es_BO",
      images: [OG_IMAGE],
    },
  };
}
